function normalizeText(value=''){return String(value).toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();}
function tokens(value=''){return new Set(normalizeText(value).split(' ').filter(Boolean));}
function overlap(a,b){const A=tokens(a),B=tokens(b);if(!A.size&&!B.size)return 1;if(!A.size||!B.size)return 0;let common=0;for(const token of A)if(B.has(token))common++;return common/Math.max(A.size,B.size);}
function attendeeSet(event){return new Set((event.attendees||[]).map(x=>normalizeText(typeof x==='string'?x:(x.email||x.name||''))).filter(Boolean));}
function attendeeOverlap(a,b){const A=attendeeSet(a),B=attendeeSet(b);if(!A.size&&!B.size)return .5;if(!A.size||!B.size)return 0;let common=0;for(const value of A)if(B.has(value))common++;return common/Math.max(A.size,B.size);}
function minutesBetween(a,b){return Math.abs(new Date(a).getTime()-new Date(b).getTime())/60000;}
function scoreCandidate(a,b){const startDiff=minutesBetween(a.start,b.start);const endDiff=minutesBetween(a.end,b.end);const timeScore=startDiff<=2&&endDiff<=2?1:startDiff<=15&&endDiff<=15?.7:startDiff<=60&&endDiff<=60?.25:0;const titleScore=overlap(a.title,b.title);const attendees=attendeeOverlap(a,b);const organizer=(normalizeText(a.organizer||'')&&normalizeText(a.organizer||'')===normalizeText(b.organizer||''))?1:0;const meeting=(a.meetingUrl&&b.meetingUrl&&normalizeText(a.meetingUrl)===normalizeText(b.meetingUrl))?1:0;const weighted=(timeScore*.42)+(titleScore*.25)+(attendees*.2)+(organizer*.08)+(meeting*.05);return Math.round(weighted*100);}
function classifyCandidate(a,b){const score=scoreCandidate(a,b);return {score,classification:score>=85?'likely_duplicate':score>=65?'review':'distinct',evidence:{startMinutes:minutesBetween(a.start,b.start),endMinutes:minutesBetween(a.end,b.end),titleOverlap:Math.round(overlap(a.title,b.title)*100),attendeeOverlap:Math.round(attendeeOverlap(a,b)*100)}};}
function buildCanonical(primary,records){return {title:primary.title,start:primary.start,end:primary.end,organizer:primary.organizer||null,attendees:primary.attendees||[],sourceRecords:[primary,...records.filter(r=>r!==primary)].map(r=>({provider:r.provider||'unknown',id:r.id||null,title:r.title,start:r.start,end:r.end})),status:'confirmed'};}
module.exports={normalizeText,scoreCandidate,classifyCandidate,buildCanonical};
